/** @format */

import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { Header } from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function Layout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
      <main
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
        )}
      >
        <div className="flex flex-col w-full">
          <Header />
          <div className="flex">
            {/* sidebar */}
            <SideNavbar />
            {/* main page */}
            <div className="p-8 w-full">{children}</div>
          </div>
        </div>
      </main>
  );
}
